/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import loveguitars.assignemnt.Employee;

/**
 *
 * @author Tatiana
 */
public class AddEmployeeFrameForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddGuitarFrameForm
     */
    public AddEmployeeFrameForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aSerialLabel = new javax.swing.JLabel();
        eIDTextField = new javax.swing.JTextField();
        aYearLabel = new javax.swing.JLabel();
        aColourLabel = new javax.swing.JLabel();
        eExtensionTextField = new javax.swing.JTextField();
        aWidthLabel = new javax.swing.JLabel();
        eRoleTextField = new javax.swing.JTextField();
        aHeightLabel = new javax.swing.JLabel();
        ePhoneTextField = new javax.swing.JTextField();
        aModelLabel = new javax.swing.JLabel();
        aBuilderLabel = new javax.swing.JLabel();
        eAddressTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        eAddButton = new javax.swing.JButton();
        aLengthLabel = new javax.swing.JLabel();
        eNameTextField = new javax.swing.JTextField();
        ePasswordTextField = new javax.swing.JTextField();
        aHeightLabel1 = new javax.swing.JLabel();
        eUsernameTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(800, 670));

        jPanel1.setBackground(new java.awt.Color(34, 41, 48));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(666, 646));

        aSerialLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aSerialLabel.setForeground(new java.awt.Color(78, 177, 186));
        aSerialLabel.setText("ID");

        aYearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aYearLabel.setForeground(new java.awt.Color(78, 177, 186));
        aYearLabel.setText("Name");

        aColourLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aColourLabel.setForeground(new java.awt.Color(78, 177, 186));
        aColourLabel.setText("Date of Birth");

        aWidthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aWidthLabel.setForeground(new java.awt.Color(78, 177, 186));
        aWidthLabel.setText("role");

        aHeightLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aHeightLabel.setForeground(new java.awt.Color(78, 177, 186));
        aHeightLabel.setText("Username");

        aModelLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aModelLabel.setForeground(new java.awt.Color(78, 177, 186));
        aModelLabel.setText("Address");

        aBuilderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aBuilderLabel.setForeground(new java.awt.Color(78, 177, 186));
        aBuilderLabel.setText("Phone");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(233, 233, 233));
        jLabel16.setText("Work details");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(233, 233, 233));
        jLabel18.setText("Personal information");

        eAddButton.setBackground(new java.awt.Color(78, 177, 186));
        eAddButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eAddButton.setForeground(new java.awt.Color(34, 41, 48));
        eAddButton.setText("Add Employee");
        eAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eAddButtonActionPerformed(evt);
            }
        });

        aLengthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aLengthLabel.setForeground(new java.awt.Color(78, 177, 186));
        aLengthLabel.setText("Phone extension");

        aHeightLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aHeightLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aHeightLabel1.setText("Password");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(233, 233, 233));
        jLabel17.setText("Login details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aSerialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aYearLabel)
                            .addComponent(eNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aBuilderLabel)
                            .addComponent(aModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aHeightLabel)
                            .addComponent(aLengthLabel)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aWidthLabel)
                            .addComponent(eRoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aHeightLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(eAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aLengthLabel)
                    .addComponent(aSerialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aYearLabel)
                    .addComponent(aWidthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRoleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aColourLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(aModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aBuilderLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aHeightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aHeightLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(eAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eAddButtonActionPerformed
        // check if entered all the data into fields
        if(eIDTextField.getText().length()<=0 ||eNameTextField.getText().length()<=0||
            eAddressTextField.getText().length()<=0||eExtensionTextField.getText().length()<=0 ||
            eRoleTextField.getText().length()<=0||ePhoneTextField.getText().length()<=0 ||
        eUsernameTextField.getText().length()<=0 ||ePasswordTextField.getText().length()<=0)   
        {JOptionPane.showMessageDialog(null, "Some fields are empty, please add more data");}
        else{
                String id=eIDTextField.getText();
                String name=eNameTextField.getText();
                Date dateOfBirth=jDateChooser1.getDate();
                String address= eAddressTextField.getText();
                String phone=ePhoneTextField.getText();
                String role=eRoleTextField.getText();
                int extension=Integer.parseInt(eExtensionTextField.getText());
                String username=eUsernameTextField.getText();
                String password=ePasswordTextField.getText();
                // create new Employee object
                Employee e= new Employee(extension, username, password, role, id, 
                        name, dateOfBirth, address, phone);
                // add new employee to the array list

                String output=Dashboard.staff.addEmployee(e, Dashboard.shop);
                JOptionPane.showMessageDialog(this, output);
                // set fields empty for next entry

                eIDTextField.setText("");
                eNameTextField.setText("");
                eAddressTextField.setText("");
                jDateChooser1.setDate(null);
                eRoleTextField.setText("");
                ePhoneTextField.setText("");
                eExtensionTextField.setText("");
                eUsernameTextField.setText("");
                ePasswordTextField.setText("");
        }
    }//GEN-LAST:event_eAddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aBuilderLabel;
    private javax.swing.JLabel aColourLabel;
    private javax.swing.JLabel aHeightLabel;
    private javax.swing.JLabel aHeightLabel1;
    private javax.swing.JLabel aLengthLabel;
    private javax.swing.JLabel aModelLabel;
    private javax.swing.JLabel aSerialLabel;
    private javax.swing.JLabel aWidthLabel;
    private javax.swing.JLabel aYearLabel;
    private javax.swing.JButton eAddButton;
    private javax.swing.JTextField eAddressTextField;
    private javax.swing.JTextField eExtensionTextField;
    private javax.swing.JTextField eIDTextField;
    private javax.swing.JTextField eNameTextField;
    private javax.swing.JTextField ePasswordTextField;
    private javax.swing.JTextField ePhoneTextField;
    private javax.swing.JTextField eRoleTextField;
    private javax.swing.JTextField eUsernameTextField;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
