/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import loveguitars.assignemnt.Build;
import loveguitars.assignemnt.Guitar;
import loveguitars.assignemnt.GuitarType;
import loveguitars.assignemnt.Wood;

/**
 *
 * @author Tatiana
 */
public class AddGuitarFrameForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddGuitarFrameForm
     */
    public AddGuitarFrameForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aSerialLabel = new javax.swing.JLabel();
        aSerialTextField = new javax.swing.JTextField();
        aYearLabel = new javax.swing.JLabel();
        aColourLabel = new javax.swing.JLabel();
        aColourTextField = new javax.swing.JTextField();
        aLengthTextField = new javax.swing.JTextField();
        aWidthLabel = new javax.swing.JLabel();
        aWidthTextField = new javax.swing.JTextField();
        aHeightLabel = new javax.swing.JLabel();
        rentTextField = new javax.swing.JTextField();
        aModelLabel = new javax.swing.JLabel();
        aBuilderLabel = new javax.swing.JLabel();
        aTypeLabel = new javax.swing.JLabel();
        aBackLabel = new javax.swing.JLabel();
        aModelTextField = new javax.swing.JTextField();
        aTopLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        aLengthLabel = new javax.swing.JLabel();
        aTypeComboBox = new javax.swing.JComboBox<>();
        aBuilderComboBox = new javax.swing.JComboBox<>();
        aBackWooldComboBox = new javax.swing.JComboBox<>();
        aTopWoodComboBox = new javax.swing.JComboBox<>();
        aYearTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        aTopLabel1 = new javax.swing.JLabel();
        aHeightTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(78, 177, 186));

        jPanel1.setBackground(new java.awt.Color(34, 41, 48));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(666, 646));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        aSerialLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aSerialLabel.setForeground(new java.awt.Color(78, 177, 186));
        aSerialLabel.setText("serial number");

        aYearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aYearLabel.setForeground(new java.awt.Color(78, 177, 186));
        aYearLabel.setText("year of manufacture");

        aColourLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aColourLabel.setForeground(new java.awt.Color(78, 177, 186));
        aColourLabel.setText("colour");

        aWidthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aWidthLabel.setForeground(new java.awt.Color(78, 177, 186));
        aWidthLabel.setText("width");

        aHeightLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aHeightLabel.setForeground(new java.awt.Color(78, 177, 186));
        aHeightLabel.setText("height");

        aModelLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aModelLabel.setForeground(new java.awt.Color(78, 177, 186));
        aModelLabel.setText("model");

        aBuilderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aBuilderLabel.setForeground(new java.awt.Color(78, 177, 186));
        aBuilderLabel.setText("builder");

        aTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aTypeLabel.setForeground(new java.awt.Color(78, 177, 186));
        aTypeLabel.setText("type");

        aBackLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aBackLabel.setForeground(new java.awt.Color(78, 177, 186));
        aBackLabel.setText("back wood");

        aTopLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aTopLabel.setForeground(new java.awt.Color(78, 177, 186));
        aTopLabel.setText("top wood");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(233, 233, 233));
        jLabel16.setText("size");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(233, 233, 233));
        jLabel18.setText("general information");

        addButton.setBackground(new java.awt.Color(78, 177, 186));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(34, 41, 48));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        aLengthLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aLengthLabel.setForeground(new java.awt.Color(78, 177, 186));
        aLengthLabel.setText("length");

        aTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACOUSTIC", "ELECTRIC" }));
        aTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTypeComboBoxActionPerformed(evt);
            }
        });

        aBuilderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FENDER", "MARTIN", "GIBSON", "COLLINGS", "OLSON", "RYAN", "PARAS", "RAJ" }));

        aBackWooldComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIAN_ROSEWOOD", "BRAZILIAN_ROSEWOOD", "MAHOGANY", "MAPLE", "COCOBOLO", "CEDAR", "ADIRONDACK", "ALDER", "SITKA" }));

        aTopWoodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIAN_ROSEWOOD", "BRAZILIAN_ROSEWOOD", "MAHOGANY", "MAPLE", "COCOBOLO", "CEDAR", "ADIRONDACK", "ALDER", "SITKA" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Wood");

        aTopLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aTopLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aTopLabel1.setText("Rent per day");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aYearLabel)
                            .addComponent(aYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aColourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aBuilderLabel)
                            .addComponent(aBuilderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aTypeLabel)
                            .addComponent(aTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aTopLabel1)
                            .addComponent(aSerialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aLengthLabel)
                            .addComponent(aLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aWidthLabel)
                            .addComponent(aWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aHeightLabel)
                            .addComponent(aHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(aBackLabel)
                            .addComponent(aBackWooldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aTopLabel)
                            .addComponent(aTopWoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(76, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(aSerialLabel)
                                    .addComponent(aLengthLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(aSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(aYearLabel)
                                    .addComponent(aWidthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(aYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aColourLabel)
                            .addComponent(aHeightLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aColourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aBackLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aBackWooldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aBuilderLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(aBuilderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(aTopLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aTopWoodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aTopLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTypeComboBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // checking if all fields have data
        String serialNumber=null; int yearOfManufacture=0; String colour=null; String model =null;
        Build builder=null;GuitarType type=null;Wood backWood=null;Wood topWood=null;
        double width=0;double height=0;double lenght=0;double rentChanrgePerDay=0;
        
         if(aSerialTextField.getText().length()<=0 ||aYearTextField.getText().length()<=0||
               aColourTextField.getText().length()<=0||aModelTextField.getText().length()<=0||
                aBuilderComboBox.getSelectedItem().toString().length()<=0||
                aBackWooldComboBox.getSelectedItem().toString().length()<=0||
                aTopWoodComboBox.getSelectedItem().toString().length()<=0||
                aWidthTextField.getText().length()<=0 ||aHeightTextField.getText().length()<=0||
                aLengthTextField.getText().length()<=0||rentTextField.getText().length()<=0 )
        {
            JOptionPane.showMessageDialog(null, "Some fields are empty, please add more data");
        }else
         {
             try{
         serialNumber=aSerialTextField.getText();
         yearOfManufacture=Integer.parseInt(aYearTextField.getText());
         colour=aColourTextField.getText();
         model=aModelTextField.getText();
         builder=Build.valueOf(aBuilderComboBox.getSelectedItem().toString()) ;
         type=GuitarType.valueOf(aTypeComboBox.getSelectedItem().toString());
         backWood=Wood.valueOf(aBackWooldComboBox.getSelectedItem().toString());
         topWood=Wood.valueOf(aTopWoodComboBox.getSelectedItem().toString());
         width=Double.parseDouble(aWidthTextField.getText());
         height=Double.parseDouble(aHeightTextField.getText());
         lenght=Double.parseDouble(aLengthTextField.getText());
         rentChanrgePerDay=Double.parseDouble(rentTextField.getText());
             }
             catch( Exception ex)
             {
                 JOptionPane.showMessageDialog(this, "Please enter correct data");
                 
             }
     // create new Guitar object
     if (serialNumber!=null&& yearOfManufacture!=0&&colour!=null && model!=null&&
             builder!=null && type!=null && backWood !=null &&topWood !=null &&
             width!=0 &&height!= 0 &&lenght!=0 && rentChanrgePerDay!=0)
     {
       Guitar g=new Guitar(serialNumber, yearOfManufacture, rentChanrgePerDay, 
               colour, lenght, width, height, model, builder, type, backWood, topWood);
       // add new guitar to the array list
       String output=Dashboard.staff.addGuitar(g, Dashboard.shop);
       JOptionPane.showMessageDialog(this, output);
      
       // set empty fields for new entry
        aSerialTextField.setText("");
        aYearTextField.setText("");
        aModelTextField.setText("");
        aColourTextField.setText("");
        aWidthTextField.setText("");
        rentTextField.setText("");
        aHeightTextField.setText("");
        aLengthTextField.setText("");
        aBuilderComboBox.setSelectedItem(null);
        aTypeComboBox.setSelectedItem(null);
        aBackWooldComboBox.setSelectedItem(null);
        aTopWoodComboBox.setSelectedItem(null);
         
         }
         }
       
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aBackLabel;
    private javax.swing.JComboBox<String> aBackWooldComboBox;
    private javax.swing.JComboBox<String> aBuilderComboBox;
    private javax.swing.JLabel aBuilderLabel;
    private javax.swing.JLabel aColourLabel;
    private javax.swing.JTextField aColourTextField;
    private javax.swing.JLabel aHeightLabel;
    private javax.swing.JTextField aHeightTextField;
    private javax.swing.JLabel aLengthLabel;
    private javax.swing.JTextField aLengthTextField;
    private javax.swing.JLabel aModelLabel;
    private javax.swing.JTextField aModelTextField;
    private javax.swing.JLabel aSerialLabel;
    private javax.swing.JTextField aSerialTextField;
    private javax.swing.JLabel aTopLabel;
    private javax.swing.JLabel aTopLabel1;
    private javax.swing.JComboBox<String> aTopWoodComboBox;
    private javax.swing.JComboBox<String> aTypeComboBox;
    private javax.swing.JLabel aTypeLabel;
    private javax.swing.JLabel aWidthLabel;
    private javax.swing.JTextField aWidthTextField;
    private javax.swing.JLabel aYearLabel;
    private javax.swing.JTextField aYearTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rentTextField;
    // End of variables declaration//GEN-END:variables
}
