/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import loveguitars.assignemnt.Customer;
import loveguitars.assignemnt.RentalRecord;

/**
 *
 * @author Tatiana
 */
public class CustomersFrameForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddGuitarFrameForm
     */
    public CustomersFrameForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        aColourLabel1 = new javax.swing.JLabel();
        startDayXDatePicker = new com.toedter.calendar.JDateChooser();
        endDatePicker = new com.toedter.calendar.JDateChooser();
        aColourLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(34, 41, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(666, 646));

        jScrollPane1.setBackground(new java.awt.Color(34, 41, 48));

        cTable.setBackground(new java.awt.Color(34, 41, 48));
        cTable.setForeground(new java.awt.Color(233, 233, 233));
        cTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date rented", "Customer ID", "Name", "Address", "Phone", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        cTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cTable.setFillsViewportHeight(true);
        cTable.setFocusable(false);
        cTable.setGridColor(new java.awt.Color(0, 0, 0));
        cTable.setRowHeight(30);
        cTable.setRowMargin(2);
        cTable.setSelectionBackground(new java.awt.Color(78, 177, 186));
        cTable.setSelectionForeground(new java.awt.Color(233, 233, 233));
        cTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(cTable);
        if (cTable.getColumnModel().getColumnCount() > 0) {
            cTable.getColumnModel().getColumn(0).setResizable(false);
            cTable.getColumnModel().getColumn(0).setPreferredWidth(90);
            cTable.getColumnModel().getColumn(2).setResizable(false);
            cTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            cTable.getColumnModel().getColumn(3).setResizable(false);
            cTable.getColumnModel().getColumn(3).setPreferredWidth(140);
        }

        searchButton.setBackground(new java.awt.Color(78, 177, 186));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchButton.setText("Display customers");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(233, 233, 233));
        jLabel21.setText("Search recrod by Date:");

        aColourLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aColourLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aColourLabel1.setText("Start date of rent");

        startDayXDatePicker.setDateFormatString("dd/MM/yyyy");
        startDayXDatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                startDayXDatePickerPropertyChange(evt);
            }
        });

        endDatePicker.setDateFormatString("dd/MM/yyyy");
        endDatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                endDatePickerPropertyChange(evt);
            }
        });

        aColourLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aColourLabel2.setForeground(new java.awt.Color(78, 177, 186));
        aColourLabel2.setText("End date of rent");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aColourLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDayXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aColourLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aColourLabel1)
                            .addComponent(aColourLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startDayXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // cretae a table
        // display rental records netween 2 selected dates
        // set simpleDateFromat to display rental dates as dates only, with no time
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        Date startDay=startDayXDatePicker.getDate();
        Date endDate=endDatePicker.getDate();
        //calling function from the shop to search for record
        RentalRecord found=Dashboard.shop.searchRecordbyDate(startDay, endDate);

        //define table
        cTable.setVisible(true);
        DefaultTableModel model=(DefaultTableModel)cTable.getModel();
        model.setNumRows(0);
        ArrayList<RentalRecord> rentals=Dashboard.shop.getRentals();
  
        Object [] rowData= new Object[6];
        for (int i=0; i<rentals.size(); i++)
        {
              // check that rent date will be between first and last day, including both days
            if (rentals.get(i).getRentDate().after(startDay)&&rentals.get(i).getRentDate().before(endDate)
                    ||rentals.get(i).getRentDate().equals(startDay)||rentals.get(i).getRentDate().equals(endDate))
            {
                // sdf format to display date as date only, with no time in it
            rowData[0]=sdf.format(rentals.get(i).getRentDate());
            rowData[1]=rentals.get(i).getCustomer().getId();
            rowData[2]=rentals.get(i).getCustomer().getName();
            rowData[3]=rentals.get(i).getCustomer().getAddress();
            rowData[4]=rentals.get(i).getCustomer().getPhoneNumber();
            rowData[5]=rentals.get(i).getCustomer().getGender();
            
            model.addRow(rowData);
             }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void startDayXDatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_startDayXDatePickerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_startDayXDatePickerPropertyChange

    private void endDatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_endDatePickerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_endDatePickerPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aColourLabel1;
    private javax.swing.JLabel aColourLabel2;
    private javax.swing.JTable cTable;
    private com.toedter.calendar.JDateChooser endDatePicker;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private com.toedter.calendar.JDateChooser startDayXDatePicker;
    // End of variables declaration//GEN-END:variables
}
