/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Dashboard;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import loveguitars.assignemnt.Customer;
import loveguitars.assignemnt.Guitar;

/**
 *
 * @author Tatiana
 */
public class RentGuitarFrameForm extends javax.swing.JInternalFrame {
    //define date format
    DateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
    Date date=new Date();
    Calendar cal=Calendar.getInstance();
    

    /**
     * Creates new form AddGuitarFrameForm
     */
    public RentGuitarFrameForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        //hide labels and text fields
        daysLabel.setVisible(false);
        priceLabel.setVisible(false);
        daysTextField.setVisible(false);
        priceTextField.setVisible(false);
        rentButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aSerialLabel = new javax.swing.JLabel();
        rentIDTextField = new javax.swing.JTextField();
        aYearLabel = new javax.swing.JLabel();
        daysTextField = new javax.swing.JTextField();
        aModelLabel = new javax.swing.JLabel();
        aBuilderLabel = new javax.swing.JLabel();
        returnSerialTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        rentSerialTextField = new javax.swing.JTextField();
        returnDueXDatePicker = new com.toedter.calendar.JDateChooser();
        returnDateXDatePicker = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        daysLabel = new javax.swing.JLabel();
        cButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        rentButton = new javax.swing.JButton();
        priceTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        aColourLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(34, 41, 48));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(638, 649));

        aSerialLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aSerialLabel.setForeground(new java.awt.Color(78, 177, 186));
        aSerialLabel.setText("ID");

        aYearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aYearLabel.setForeground(new java.awt.Color(78, 177, 186));
        aYearLabel.setText("Serial number");

        daysTextField.setEditable(false);
        daysTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysTextFieldActionPerformed(evt);
            }
        });

        aModelLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aModelLabel.setForeground(new java.awt.Color(78, 177, 186));
        aModelLabel.setText("Serial number");

        aBuilderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aBuilderLabel.setForeground(new java.awt.Color(78, 177, 186));
        aBuilderLabel.setText("Return Date");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(233, 233, 233));
        jLabel18.setText("Guitar information");

        returnButton.setBackground(new java.awt.Color(78, 177, 186));
        returnButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        returnButton.setForeground(new java.awt.Color(34, 41, 48));
        returnButton.setText("Return Guitar");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        returnDueXDatePicker.setDateFormatString("dd/MM/yyyy");
        returnDueXDatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                returnDueXDatePickerPropertyChange(evt);
            }
        });

        returnDateXDatePicker.setDateFormatString("dd/MM/yyyy");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(78, 177, 186));
        jLabel19.setText("Return Guitar form");

        daysLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        daysLabel.setForeground(new java.awt.Color(78, 177, 186));
        daysLabel.setText("Total days");

        cButton.setBackground(new java.awt.Color(78, 177, 186));
        cButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cButton.setForeground(new java.awt.Color(34, 41, 48));
        cButton.setText("Calculate Price");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(233, 233, 233));
        jLabel20.setText("Customer details:");

        rentButton.setBackground(new java.awt.Color(78, 177, 186));
        rentButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rentButton.setForeground(new java.awt.Color(34, 41, 48));
        rentButton.setText("Rent Guitar");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        priceTextField.setEditable(false);
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(78, 177, 186));
        priceLabel.setText("Price");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(78, 177, 186));
        jLabel21.setText("Rent guitar form");

        aColourLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aColourLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aColourLabel1.setText("Return Due Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aSerialLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rentIDTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rentSerialTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(returnDueXDatePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aBuilderLabel)
                                    .addComponent(returnDateXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(returnSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(98, 98, 98))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(daysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(daysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceLabel)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aColourLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aYearLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aSerialLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(9, 9, 9)
                        .addComponent(aYearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rentSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aColourLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(aModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(returnSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aBuilderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnDateXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnDueXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daysLabel)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // return guitar button action
        String serialNumber=null;Date returnDate=null;
        try{
        serialNumber=returnSerialTextField.getText();
        returnDate=returnDateXDatePicker.getDate();
        }
        catch (Exception chekData)
        {
            JOptionPane.showMessageDialog(this, "Please enter correct data");
        }
       if(returnDate==null)
       {
           JOptionPane.showMessageDialog(this, "Please enter the Date");
       }else
        //get a message from the shop, if customer should pay outstanding fees 

         {
         String output=Dashboard.shop.returnGuitar(serialNumber, returnDate);
         JOptionPane.showMessageDialog(this, output); 
         
         returnSerialTextField.setText("");
         returnDateXDatePicker.setDate(null);
         }
    }//GEN-LAST:event_returnButtonActionPerformed

    private void returnDueXDatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_returnDueXDatePickerPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_returnDueXDatePickerPropertyChange

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // calcultae price button, after pressing on this button staff can see the total price and rent guitar
        
         if (returnDueXDatePicker.getDate()==null|| rentSerialTextField.getText().length()<0||
                rentIDTextField.getText().length()<0 )
        {
            JOptionPane.showMessageDialog(null, "Some fields are empty");
        }
        
        daysLabel.setVisible(true);
        priceLabel.setVisible(true);
        daysTextField.setVisible(true);
        priceTextField.setVisible(true);
        rentButton.setVisible(true);
        
       String serialNumber=null; String id=null; Date rentDueDate1=null;
       
        try{
       serialNumber =rentSerialTextField.getText();
       id=rentIDTextField.getText();
       rentDueDate1=returnDueXDatePicker.getDate();
     
      }
      catch( Exception wrongData)
      {
          JOptionPane.showMessageDialog(this, "Please enter correct input");
      }
    
        //search if guitar exists in the system
        Guitar guitar=Dashboard.staff.searchGuitar(serialNumber, Dashboard.shop);
        if (guitar==null)
          {
            JOptionPane.showMessageDialog(this, "No guitar found");
        }else
        {
           
            //check if customer exists in the system
            Customer customer=Dashboard.staff.searchCustomer(id, Dashboard.shop);
            if (customer==null)
          {
            JOptionPane.showMessageDialog(this, "No customer found");
            //check if rent due date not empty
        }
        if(rentDueDate1==null)
       {
           JOptionPane.showMessageDialog(this, "Please enter the Date");
       }else
            {          
                LocalDate rentDate=LocalDate.now();
                //check if date from future
                long days=Dashboard.shop.calculateDays(rentDueDate1,rentDate);
                if (days>=0)
                {  
                daysTextField.setText(days+"");  
                double rentPerDay=guitar.getRentChanrgePerDay();
                //calculate price for rent period
                double total=Double.parseDouble(new DecimalFormat("##.##").format(rentPerDay*days));
                priceTextField.setText(total+"");
            }
                else{ 
            JOptionPane.showMessageDialog(this, "Choose a date in the future");
            }
                
            }
        }
        
        
    }//GEN-LAST:event_cButtonActionPerformed

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
        //if customer agrees to the price and date, staff can rent the guitar
     if (returnDueXDatePicker.getDate()==null|| rentSerialTextField.getText().length()<0||
                rentIDTextField.getText().length()<0 )
        {
            JOptionPane.showMessageDialog(null, "Some fields are empty");
        }
        
        String serialNumber=null; String id=null; Date rentDueDate1=null;
        try{
       serialNumber =rentSerialTextField.getText();
       id=rentIDTextField.getText();
       rentDueDate1=returnDueXDatePicker.getDate();
      }
      catch( Exception wrongData)
      {
          JOptionPane.showMessageDialog(this, "Please enter correct input");
      }
       //calling rentGuitar method, to check if guitar is available for rent and add it in the array list of rental records
       if(rentDueDate1==null)
       {
           JOptionPane.showMessageDialog(this, "Please enter the Date");
       }else 
       {
           String output = Dashboard.staff.rentGuitar(id, serialNumber, Dashboard.shop, rentDueDate1); 

       JOptionPane.showMessageDialog(this, output);

        daysLabel.setVisible(false);
        priceLabel.setVisible(false);
        daysTextField.setVisible(false);
        priceTextField.setVisible(false);
        rentButton.setVisible(false);
        rentSerialTextField.setText("");
        rentIDTextField.setText("");
        returnDueXDatePicker.setDate(null);
    }//GEN-LAST:event_rentButtonActionPerformed
    }
    private void daysTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aBuilderLabel;
    private javax.swing.JLabel aColourLabel1;
    private javax.swing.JLabel aModelLabel;
    private javax.swing.JLabel aSerialLabel;
    private javax.swing.JLabel aYearLabel;
    private javax.swing.JButton cButton;
    private javax.swing.JLabel daysLabel;
    private javax.swing.JTextField daysTextField;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton rentButton;
    private javax.swing.JTextField rentIDTextField;
    private javax.swing.JTextField rentSerialTextField;
    private javax.swing.JButton returnButton;
    private com.toedter.calendar.JDateChooser returnDateXDatePicker;
    private com.toedter.calendar.JDateChooser returnDueXDatePicker;
    private javax.swing.JTextField returnSerialTextField;
    // End of variables declaration//GEN-END:variables
}
