/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Dashboard;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import loveguitars.assignemnt.Guitar;

/**
 *
 * @author Tatiana
 */
public class SearchGuitarFrameForm1 extends javax.swing.JInternalFrame {
    

    /**
     * Creates new form AddGuitarFrameForm
     */
    public SearchGuitarFrameForm1() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        sPanel.setVisible(false);
        //sent data fields invisible     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sSerialLabel = new javax.swing.JLabel();
        sSerialTextField = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        sPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        sLengthLabel1 = new javax.swing.JLabel();
        sLengthTextField = new javax.swing.JTextField();
        sWidthLabel1 = new javax.swing.JLabel();
        sWidthTextField = new javax.swing.JTextField();
        sHeigthLabel1 = new javax.swing.JLabel();
        sHeightTextField = new javax.swing.JTextField();
        sColourLabel = new javax.swing.JLabel();
        sColourTextField = new javax.swing.JTextField();
        sRentLabel = new javax.swing.JLabel();
        sRentTextField = new javax.swing.JTextField();
        sStatusComboBox = new javax.swing.JComboBox<>();
        sStatusLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(34, 41, 48));

        jPanel2.setBackground(new java.awt.Color(34, 41, 48));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(666, 646));

        sSerialLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sSerialLabel.setForeground(new java.awt.Color(78, 177, 186));
        sSerialLabel.setText("Serial number");

        resetButton.setBackground(new java.awt.Color(78, 177, 186));
        resetButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(78, 177, 186));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(78, 177, 186));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        sPanel.setBackground(new java.awt.Color(34, 41, 48));
        sPanel.setPreferredSize(new java.awt.Dimension(800, 670));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(233, 233, 233));
        jLabel17.setText("size");

        sLengthLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sLengthLabel1.setForeground(new java.awt.Color(78, 177, 186));
        sLengthLabel1.setText("length");

        sWidthLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sWidthLabel1.setForeground(new java.awt.Color(78, 177, 186));
        sWidthLabel1.setText("width");

        sHeigthLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sHeigthLabel1.setForeground(new java.awt.Color(78, 177, 186));
        sHeigthLabel1.setText("heigth");

        sColourLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sColourLabel.setForeground(new java.awt.Color(78, 177, 186));
        sColourLabel.setText("Colour");

        sRentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sRentLabel.setForeground(new java.awt.Color(78, 177, 186));
        sRentLabel.setText("Rent per day");

        sRentTextField.setEditable(false);

        sStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On the shop", "Rented out", "Under maintenance" }));

        sStatusLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sStatusLabel1.setForeground(new java.awt.Color(78, 177, 186));
        sStatusLabel1.setText("Status");

        javax.swing.GroupLayout sPanelLayout = new javax.swing.GroupLayout(sPanel);
        sPanel.setLayout(sPanelLayout);
        sPanelLayout.setHorizontalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sColourLabel)
                    .addComponent(sColourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRentLabel)
                    .addComponent(sRentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sStatusLabel1))
                .addGap(48, 48, 48)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sHeigthLabel1)
                    .addComponent(sLengthLabel1)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sWidthLabel1))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        sPanelLayout.setVerticalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanelLayout.createSequentialGroup()
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sLengthLabel1)
                            .addComponent(sColourLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sColourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sWidthLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(sWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(sRentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sRentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sHeigthLabel1)
                    .addComponent(sStatusLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sSerialLabel)
                    .addComponent(sSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sSerialLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // reset button emty the fields serial number and sets other fields invisible
       sSerialTextField.setText("");
       sPanel.setVisible(false);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // search guitar
        
        String ID =sSerialTextField.getText();
        //staf searching guitar from the shop array list
        Guitar guitar=Dashboard.staff.searchGuitar(ID, Dashboard.shop);
        if (guitar==null)
          {
            JOptionPane.showMessageDialog(this, "No guitar found");
        }else
        {
            sPanel.setVisible(true);
            sColourTextField.setText(guitar.getColour());
            sRentTextField.setText(guitar.getRentChanrgePerDay()+"");
            sStatusComboBox.setSelectedItem(guitar.getStatus());
           
            sRentTextField.setText(guitar.getRentChanrgePerDay()+"");
            sLengthTextField.setText(guitar.getLenght()+"");
            sWidthTextField.setText(guitar.getWidth()+"");
            sHeightTextField.setText(guitar.getHeight()+"");  
       
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // updater button can be used only after search button

        if(sSerialTextField.getText().length()<=0||sRentTextField.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please enter Guitar ID");
        }else
        {
 
       String ID =sSerialTextField.getText();
       Guitar guitar=Dashboard.staff.searchGuitar(ID, Dashboard.shop); 
       //fields which can be changed
       guitar.setColour(sColourTextField.getText());
       guitar.setLenght(Double.parseDouble(sLengthTextField.getText()));
       guitar.setHeight(Double.parseDouble(sHeightTextField.getText()));
       guitar.setWidth(Double.parseDouble(sWidthTextField.getText()));
       JOptionPane.showMessageDialog(this, "Guitar updated sucessfully");
       sSerialTextField.setText("");
       sPanel.setVisible(false);
    }//GEN-LAST:event_updateButtonActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel sColourLabel;
    private javax.swing.JTextField sColourTextField;
    private javax.swing.JTextField sHeightTextField;
    private javax.swing.JLabel sHeigthLabel1;
    private javax.swing.JLabel sLengthLabel1;
    private javax.swing.JTextField sLengthTextField;
    private javax.swing.JPanel sPanel;
    private javax.swing.JLabel sRentLabel;
    private javax.swing.JTextField sRentTextField;
    private javax.swing.JLabel sSerialLabel;
    private javax.swing.JTextField sSerialTextField;
    private javax.swing.JComboBox<String> sStatusComboBox;
    private javax.swing.JLabel sStatusLabel1;
    private javax.swing.JLabel sWidthLabel1;
    private javax.swing.JTextField sWidthTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
