/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Dashboard;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import loveguitars.assignemnt.Customer;
import loveguitars.assignemnt.Person;

/**
 *
 * @author Tatiana
 */
public class SearchCustomerFrameForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddGuitarFrameForm
     */
    public SearchCustomerFrameForm() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui= (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        //set customer data fields invisible
        sPanel.setVisible(false);
        customerPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        aSerialLabel1 = new javax.swing.JLabel();
        iDTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        sPanel = new javax.swing.JPanel();
        aColourLabel1 = new javax.swing.JLabel();
        dbirthXDatePicker = new com.toedter.calendar.JDateChooser();
        aYearLabel1 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        aModelLabel1 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        aBuilderLabel1 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        customerPanel = new javax.swing.JPanel();
        aWidthLabel3 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        aWidthLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        aLengthLabel1 = new javax.swing.JLabel();
        licenseTextField = new javax.swing.JTextField();
        aHeightLabel1 = new javax.swing.JLabel();
        expiryXDatePicker = new com.toedter.calendar.JDateChooser();
        genderComboBox = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(34, 41, 48));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(666, 646));

        aSerialLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aSerialLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aSerialLabel1.setText("ID");

        searchButton.setBackground(new java.awt.Color(78, 177, 186));
        searchButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(78, 177, 186));
        resetButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(78, 177, 186));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        sPanel.setBackground(new java.awt.Color(34, 41, 48));

        aColourLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aColourLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aColourLabel1.setText("Date of Birth");

        dbirthXDatePicker.setDateFormatString("dd/MM/yyyy");
        dbirthXDatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dbirthXDatePickerPropertyChange(evt);
            }
        });

        aYearLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aYearLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aYearLabel1.setText("Name");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(233, 233, 233));
        jLabel20.setText("Personal information");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(233, 233, 233));
        jLabel21.setText("Contact details");

        aModelLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aModelLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aModelLabel1.setText("Address");

        aBuilderLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aBuilderLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aBuilderLabel1.setText("Phone");

        customerPanel.setBackground(new java.awt.Color(34, 41, 48));

        aWidthLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aWidthLabel3.setForeground(new java.awt.Color(78, 177, 186));
        aWidthLabel3.setText("Age");

        ageTextField.setEditable(false);

        aWidthLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aWidthLabel2.setForeground(new java.awt.Color(78, 177, 186));
        aWidthLabel2.setText("Gender");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(233, 233, 233));
        jLabel17.setText("License details");

        aLengthLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aLengthLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aLengthLabel1.setText("License Number");

        aHeightLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aHeightLabel1.setForeground(new java.awt.Color(78, 177, 186));
        aHeightLabel1.setText("License Expiry date");

        expiryXDatePicker.setDateFormatString("dd/MM/yyyy");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aWidthLabel3)
                    .addComponent(aWidthLabel2)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expiryXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLengthLabel1)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aHeightLabel1))
                .addGap(107, 107, 107))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(aWidthLabel3))
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(aHeightLabel1))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aLengthLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aWidthLabel2)
                            .addComponent(licenseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expiryXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sPanelLayout = new javax.swing.GroupLayout(sPanel);
        sPanel.setLayout(sPanelLayout);
        sPanelLayout.setHorizontalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aYearLabel1)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aColourLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbirthXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aBuilderLabel1)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aModelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sPanelLayout.setVerticalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aModelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aYearLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aBuilderLabel1)
                    .addComponent(aColourLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbirthXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aSerialLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(aSerialLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(sPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbirthXDatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dbirthXDatePickerPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_dbirthXDatePickerPropertyChange

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:

        String ID =iDTextField.getText();
        //search for a customer in the array list
        Person person=Dashboard.staff.searchCustomer(ID, Dashboard.shop);
        if (person==null)
        {
            JOptionPane.showMessageDialog(this, "No customer found");
        }else
        {
            {//display data
            sPanel.setVisible(true);
            NameTextField.setText(person.getName());
            dbirthXDatePicker.setDate(person.getDateOfBirth());
            addressTextField.setText(person.getAddress());
            phoneTextField.setText(person.getPhoneNumber());
        
            Customer c=(Customer)person;
            customerPanel.setVisible(true);
            ageTextField.setText(c.getAge()+"");
            if(c.getGender()=='M')
                    {
            genderComboBox.setSelectedItem("MALE");
                    }else
            {
                genderComboBox.setSelectedItem("FEMALE");
            }
            licenseTextField.setText(c.getLicenseNumber());
            expiryXDatePicker.setDate(c.getLicenseExpiryDate());
            
        }    
        }    
    }//GEN-LAST:event_searchButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // reset button empy the fields and hides data fields
        iDTextField.setText("");
        sPanel.setVisible(false);
        customerPanel.setVisible(false);
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // updata data filed can be used only after search button
        if(iDTextField.getText().length()<=0||NameTextField.getText().length()<=0||
                ageTextField.getText().length()<=0)
        {
            JOptionPane.showMessageDialog(null, "Please enter Customer ID");
        }else
        { 
        String id=iDTextField.getText();
        Customer customer=Dashboard.staff.searchCustomer(id, Dashboard.shop);
        sPanel.setVisible(true);
        customerPanel.setVisible(true);
        //fields which can be modified
        customer.setPhoneNumber(phoneTextField.getText());
        customer.setName(NameTextField.getText());
        customer.setAddress(addressTextField.getText());
        customer.setId(iDTextField.getText());
        customer.setLicenseNumber(licenseTextField.getText());
        
        //cheching if ID expiry date not past today date
            long days=Dashboard.shop.checkID(expiryXDatePicker.getDate());
            if(days>=0)
            {
                JOptionPane.showMessageDialog(this, "Please update document expiry date");
            }else{
        customer.setLicenseExpiryDate(expiryXDatePicker.getDate());
        JOptionPane.showMessageDialog(this, "Customer updated sucesfully");
        //hide everything and sent id text field empty for new entry
        sPanel.setVisible(false);
        customerPanel.setVisible(false);
        iDTextField.setText("");
            }
    }//GEN-LAST:event_updateButtonActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel aBuilderLabel1;
    private javax.swing.JLabel aColourLabel1;
    private javax.swing.JLabel aHeightLabel1;
    private javax.swing.JLabel aLengthLabel1;
    private javax.swing.JLabel aModelLabel1;
    private javax.swing.JLabel aSerialLabel1;
    private javax.swing.JLabel aWidthLabel2;
    private javax.swing.JLabel aWidthLabel3;
    private javax.swing.JLabel aYearLabel1;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JPanel customerPanel;
    private com.toedter.calendar.JDateChooser dbirthXDatePicker;
    private com.toedter.calendar.JDateChooser expiryXDatePicker;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField iDTextField;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField licenseTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JPanel sPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
